In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.describe(include = 'number')

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [6]:
df.describe(include = 'object')

        Gender
count      400
unique       2
top     Female
freq       204

In [7]:
df['Gender'] = df['Gender'].replace({'Male' : 0, 'Female' : 1});

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    int64
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(5)
memory usage: 15.8 KB

In [9]:
X = df.drop(['Purchased'], axis = 1)
y = df['Purchased']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [11]:
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [13]:
y_pred      = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

print(y_pred)
print(y_pred_proba)

[0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0
 0 1 0 1 0 0 0 0 0]
[[0.71371014 0.28628986]
 [0.16011447 0.83988553]
 [0.91310351 0.08689649]
 [0.32301893 0.67698107]
 [0.93252975 0.06747025]
 [0.85470272 0.14529728]
 [0.31902848 0.68097152]
 [0.81615893 0.18384107]
 [0.60662206 0.39337794]
 [0.62670748 0.37329252]
 [0.77682729 0.22317271]
 [0.46283368 0.53716632]
 [0.94347789 0.05652211]
 [0.9779611  0.0220389 ]
 [0.78179004 0.21820996]
 [0.5722601  0.4277399 ]
 [0.51152966 0.48847034]
 [0.50521124 0.49478876]
 [0.76798327 0.23201673]
 [0.25821393 0.74178607]
 [0.96525788 0.03474212]
 [0.82417047 0.17582953]
 [0.68981798 0.31018202]
 [0.18152813 0.81847187]
 [0.9792963  0.0207037 ]
 [0.56385168 0.43614832]
 [0.52628492 0.47371508]
 [0.78137863 0.21862137]
 [0.11971665 0.88028335]
 [0.9794168  0.0205832 ]
 [0.63565756 0.36434244]
 [0.94510374 0.05489626]
 [0.39841175 0.60158825]
 [0.82679546 0.17320454]
 [0.4334931  0.5665069 ]
 [0.73357871 0.26642129]
 [0.74765797 0.25234203]
 [0.71791332 0.28208668]
 [0.94031831 0.05968169]
 [0.95603867 0.04396133]
 [0.60440653 0.39559347]
 [0.9369501  0.0630499 ]
 [0.96135631 0.03864369]
 [0.69389151 0.30610849]
 [0.95659499 0.04340501]
 [0.2458377  0.7541623 ]
 [0.86129626 0.13870374]
 [0.82000137 0.17999863]
 [0.55669783 0.44330217]
 [0.87195348 0.12804652]
 [0.8692538  0.1307462 ]
 [0.28927632 0.71072368]
 [0.73745452 0.26254548]
 [0.87177051 0.12822949]
 [0.66379017 0.33620983]
 [0.9371257  0.0628743 ]
 [0.10838533 0.89161467]
 [0.75734087 0.24265913]
 [0.82623525 0.17376475]
 [0.80288691 0.19711309]
 [0.71449228 0.28550772]
 [0.82613842 0.17386158]
 [0.25330663 0.74669337]
 [0.83754643 0.16245357]
 [0.89626341 0.10373659]
 [0.67545574 0.32454426]
 [0.53879008 0.46120992]
 [0.17231956 0.82768044]
 [0.71123891 0.28876109]
 [0.62066671 0.37933329]
 [0.11700554 0.88299446]
 [0.91807876 0.08192124]
 [0.89557129 0.10442871]
 [0.96746948 0.03253052]
 [0.62496633 0.37503367]
 [0.83501338 0.16498662]
 [0.08637144 0.91362856]
 [0.51205642 0.48794358]
 [0.84642138 0.15357862]
 [0.6894116  0.3105884 ]
 [0.91553043 0.08446957]
 [0.66837792 0.33162208]
 [0.37582623 0.62417377]
 [0.66666447 0.33333553]
 [0.41538244 0.58461756]
 [0.63916661 0.36083339]
 [0.68032267 0.31967733]
 [0.40959234 0.59040766]
 [0.84944041 0.15055959]
 [0.9081824  0.0918176 ]
 [0.34549548 0.65450452]
 [0.81361957 0.18638043]
 [0.69343076 0.30656924]
 [0.56322865 0.43677135]
 [0.95690525 0.04309475]
 [0.62956275 0.37043725]
 [0.06614508 0.93385492]
 [0.6142313  0.3857687 ]
 [0.0978548  0.9021452 ]
 [0.60866377 0.39133623]
 [0.09495546 0.90504454]
 [0.68213579 0.31786421]
 [0.65057107 0.34942893]
 [0.96317313 0.03682687]
 [0.82239761 0.17760239]
 [0.49521625 0.50478375]
 [0.65479363 0.34520637]
 [0.71755274 0.28244726]
 [0.305141   0.694859  ]
 [0.71404361 0.28595639]
 [0.87510031 0.12489969]
 [0.67045146 0.32954854]
 [0.40154169 0.59845831]
 [0.55972737 0.44027263]
 [0.38032662 0.61967338]
 [0.94210984 0.05789016]
 [0.96092483 0.03907517]
 [0.62040468 0.37959532]
 [0.63491417 0.36508583]
 [0.78137968 0.21862032]]

In [14]:
confusion = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

report = classification_report(y_test, y_pred)

print(confusion)

print('precision:', precision)
print('recall   :', recall)
print('f1       :', f1)

print('-' * 50)

print(report)

[[73  0]
 [20 27]]
precision: 1.0
recall   : 0.574468085106383
f1       : 0.7297297297297297
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.78      1.00      0.88        73
           1       1.00      0.57      0.73        47

    accuracy                           0.83       120
   macro avg       0.89      0.79      0.80       120
weighted avg       0.87      0.83      0.82       120